services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app # Monte le dossier actuel dans le conteneur
      - /app/node_modules # Évite les conflits avec node_modules de l'hôte
    environment:
      NODE_ENV: development

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nom_de_la_base
    ports:
      - "5432:5432" # Expose le port 5432 pour PostgreSQL
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: